import { createRoot } from 'react-dom/client';
import '@fontsource/barlow-condensed/latin-900.css';
import '@fontsource/barlow-condensed/latin-900-italic.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import '@fontsource/caveat/latin-500.css';
import App from './App';
import './styles.css';
createRoot(document.getElementById('root')!).render(<App/>);
